name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0/60 * * * 0,3,6"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: patrickcurl/wakabox@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: a7c1a53bb96a29d3d143d25c370ca962
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
